package com.kmbank.common.exception;

public enum ErrorCode {
    SUCCESS,
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    UNAUTHORIZED,
    ACCESS_DENIED,
    USER_LOCKED,
    USER_DISABLED,
    USER_NOT_FOUND,
    RESOURCE_NOT_FOUND,
    INTERNAL_SERVER_ERROR
}
